### ISSUE TITLE
Implement throttling

### ISSUE THREAD

**Issue by qezz** [ChorusOne/fastsync#1]
Currently, even with 1 connection, fastsync triggers OVH's DDoS protection system, which limits the through put significantly

We want to avoid these events if possible.

**Comment by DavidVentura** [comment]
Is it OK to only implement this from the sending side, or do you think it's valuable to specify the limit on the receiver as well?

**Comment by qezz** [comment]
I don't have enough knowledge to say for sure. Implementing it on server side sounds reasonable.
