### ISSUE TITLE
Add a version number to the wire protocol

### ISSUE THREAD

**Issue by ruuda** [ChorusOne/fastsync#4]
As brought up by @kucharskim, as a safety precaution, so we don’t connect sender version X to receiver version Y, the wire protocol should include something that identifies the version so we can exit if there is a mismatch. We don’t have to care about backwards compatibility, we can just fail on mismatch.

**Comment by DavidVentura** [comment]
The easiest way to implement the wire protocol guard would be to add the protocol version on `ChunkHeader`, though that would add 1 byte of overhead every 262KiB (`MAX_CHUNK_LEN`), along with an extra branch per chunk.

Is that OK? Alternatively, we could add a second type of message which is only transferred upon establishing each TCP connection
